name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.2.0
        with:
          # In order to avoid:
          # ./core/teststat.py:49:20: F821 undefined name 'MessageEnum'
          # ./core/teststat.py:52:20: F821 undefined name 'MessageEnum'
          ignore: "F821"
          ignore: "W503"
          max-line-length: "100"